### ISSUE TITLE
Undefined Function:  fcb_block_styles()

### ISSUE THREAD

**Issue by kenzik** [MWDelaney/acf-flexible-content-blocks#2]
After merging your the last couple months of your upstream changes to my fork, I wanted to test out the new layouts, notably tabs. Everything seems straightforward in the back-end when setting up the content.

When rendering though, it's reporting that it can' find the fcb_block_styles() function.

**Comment by MWDelaney** [comment]
This function name was changed. Do you have custom template files in your theme? If so, you'll need to change that function call to `fcb_block_wrapper_styles()`

This is one of the downfalls of how heavily in-development this tool is :/

**Comment by kenzik** [comment]
Naw, I was using standard WP while testing out the plugin. The plugin generated the error. It probably needs the new function referenced in the tabs partial. I'll see about a PR when I'm back in the code, unless you find it first.

**Comment by MWDelaney** [comment]
Blargh. Yeah. I'll see if I can find it and I'll try to do better about not committing partial features!
